name: learn_notes
description: Aplikasi Catatan Belajar berbasis Flutter untuk mendukung proses pembelajaran mahasiswa.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Core
  cupertino_icons: ^1.0.6
  provider: ^6.1.1

  # HTTP & API
  http: ^1.1.0

  # Database & Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2

  # Utilities
  intl: ^0.18.1

  # Animations
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  sqflite_common_ffi: ^2.3.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins

  generate: true

# =========================
# LAUNCHER ICON CONFIG
# =========================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
